<?php
/**
 * Generate The Request Image
 * All images are based on the largest image which one we insert into database
 * The images are generated by the client's request,
 * For example
 *    $curl http://www.xxx.com/products_name_300*300.jpg
 * if this file exists in our server, we return it,
 * otherwise we generate this file
 * 
 * @author Mobanbase.com
 * 
 */

class ImageMarker
{

    function __construct()
    {}
}

?>